### ISSUE TITLE
console.log in dist

### ISSUE THREAD

**Issue by TheJaredWilcurt** [bfiessinger/scrollToSmooth#10]
added in last release:

* https://github.com/bfiessinger/scrollToSmooth/commit/872191a6adc9a02366ecbaa3762dcdf5410a8e75#diff-969f056e85a7d23f1fa9725f5e384447004670c88820ee94ffec56a4f2c4caac

**Comment by bfiessinger** [comment]
Thanks for reporting this. I've resolved it in bc17cfd and published a new version
