### ISSUE TITLE
font-awesome icons not working with anchor href targetAttribute.

### ISSUE THREAD

**Issue by IvanMendieta** [bfiessinger/scrollToSmooth#2]
It seems that there is not an option for icons, in this case font-awesome icons, its there is an option provided to solve this issue ? 

When you click on a anchor attribute, to scroll to destination, it breaks. only does it with anchors but not if you click on the icon itself.
Ex:
```
  <a id="scroll-Btn" data-easing="linear" href="#top">
      <i class="fas fa-hand-point-up fa-2x"></i> <!-- this wont work onclick -->
    </a>
```

**Comment by yw-teh** [comment]
Hello, could i know how to set a offset to every specific section?
